include ../include.mk

NAME	:= PollSock
SOURCES	+= 				\
	constructors.cpp	\
	onConnection.cpp	\
	onData.cpp			\
	onDisconnect.cpp	\
	onWritable.cpp		\
	onError.cpp			\
	overloads.cpp		\
	listen.cpp			\
	_onPOLLIN.cpp

include $(MK)class.mk
