include ../include.mk

vpath	%.cpp handlers

NAME	:= ResponseHandler
SOURCES	:= 							\
			_onPOLLHUP.cpp			\
			_onPOLLERR.cpp			\
			constructors.cpp		\
			deconstructor.cpp		\
			delete_internal_handler.cpp \
			unregister_internal_handler.cpp \
			close_internal_handler.cpp \
			handleRedirection.cpp	\
			handleCGI.cpp			\
			handleGET.cpp			\
			handlePOST.cpp			\
			handleDELETE.cpp		\
			handleError.cpp			\
			handleResponse.cpp		\
			handleResponse.cpp		\
			getFileLength.cpp		\
			getMaxBodySize.cpp		\
			resolvedRequestPath.cpp	\
			getPostFilename.cpp		\
			get_mime.cpp			\
			getLocation.cpp			\
			getServerConfig.cpp		\
			setStatusLine.cpp		\
			setContentLength.cpp	\
			setContentType.cpp		\
			setHeader.cpp			\
			sealHeaders.cpp			\
			isCGI.cpp				\
			isRedirection.cpp		\
			openRegularFile.cpp		\
			openErrorPage.cpp		\
			isMethodAllowed.cpp		\
			on_nothing_to_write.cpp	\
			on_eof_callback.cpp \
			on_read_error_callback.cpp \


include	$(MK)class.mk
