include ../include.mk

vpath	%.cpp handlers

NAME	:= ResponseHandler
SOURCES	:= 							\
			constructors.cpp		\
			handleRedirection.cpp	\
			handleCGI.cpp			\
			handleGET.cpp			\
			handlePOST.cpp			\
			handleDELETE.cpp		\
			handleResponse.cpp		\
			handleInvalidMethod.cpp	\
			handleResponse.cpp		\
			getFileLength.cpp		\
			getMaxBodySize.cpp		\
			getRequestPath.cpp		\
			getFilename.cpp			\
			get_mime.cpp			\
			getLocation.cpp			\
			getErrorPageFd.cpp		\
			getServerConfig.cpp		\
			setStatusLine.cpp		\
			setContentLength.cpp	\
			setContentType.cpp	\
			setHeader.cpp			\
			setErrorResponse.cpp	\
			sealHeaders.cpp			\
			isCGI.cpp				\
			isRedirection.cpp		\
			openReg.cpp				\
			isMethodAllowed.cpp

include	$(MK)class.mk
