include	../include.mk

NAME	:= Socket

SOURCES	:=				\
	close.cpp			\
	read.cpp			\
	write.cpp			\
	accept.cpp			\
	bind.cpp			\
	listen.cpp			\
	connect.cpp			\
	constructors.cpp	\

include $(MK)class.mk
