include ../include.mk

NAME	:= Address

CPPSOURCES	:= 			\
	getaddrinfo	 		\
	port				\
	host 				\
	len					\
	family				\
	ptr					\
	constructors		\
	configure			\
	non-member			\
	orthodox			\


include $(MK)class.mk

test: Address.a
