server {
	host			127.0.0.1; #For docker 0.0.0.0 otherwise 127.0.0.1
	listen			8080;
	max_body_size	4096;
	error_page 404	../www/error-pages/404.html;

	location / {
		root		../www;
		index index.html;
		methods GET;
	}

}
