include	../include.mk

NAME	:= Client
SOURCES	:= \
	constructors.cpp \
	onDisconnect.cpp \
	destroy.cpp \
	onError.cpp \
	fd.cpp \
	_onPOLLIN.cpp \
	_onPOLLOUT.cpp \
	_onPOLLHUP.cpp \
	_onPOLLERR.cpp

include	$(MK)class.mk
